### ISSUE TITLE
wush ssh panic use custom derper

### ISSUE THREAD

**Issue by ysicing** [coder/wush#54]
```
Auth information:
	> Server overlay STUN address:  Disabled
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb7b656]

goroutine 1 [running]:
github.com/coder/wush/overlay.(*ClientAuth).PrintDebug(0xc0005ac7a8, 0xc00039ce10, 0xc00039c9a8)
	github.com/coder/wush/overlay/auth.go:42 +0x216
main.sshCmd.sendOverlayMW.func6.1(0xc0003b8a00)
	github.com/coder/wush/cmd/wush/cp.go:84 +0x15e
main.sshCmd.derpMap.func5.1(0xc0003b8a00)
	github.com/coder/wush/cmd/wush/cp.go:111 +0x173
main.sshCmd.initAuth.func4.1(0xc0003b8a00)
	github.com/coder/wush/cmd/wush/cp.go:65 +0x113
main.sshCmd.initLogger.func3.1(0xc0003b8a00)
	github.com/coder/wush/cmd/wush/cp.go:42 +0x15f
github.com/coder/serpent.(*Invocation).run(0xc0003b8a00, 0xc000277bd0)
	github.com/coder/serpent@v0.8.0/command.go:487 +0x10c3
github.com/coder/serpent.(*Invocation).run(0xc0003b8500, 0xc000277bd0)
	github.com/coder/serpent@v0.8.0/command.go:407 +0x934
github.com/coder/serpent.(*Invocation).Run(0xc0003b8500)
	github.com/coder/serpent@v0.8.0/command.go:582 +0x185
main.main()
	github.com/coder/wush/cmd/wush/main.go:65 +0x62d
```

**Comment by coadler** [comment]
Thanks for reporting @ysicing. Are you able to share the custom DERP json you used?

**Comment by coadler** [comment]
Ah, I think I see what went wrong. You have to specify the same DERP map on both the client and server. I'll add some checks to make sure they're the same.

**Comment by ysicing** [comment]
I exported a JSON file using the command `tailscale debug derp-map > derp.map.json`, which contains my custom DERP settings. Below are some examples of my DERP configurations. All of my DERPs have the `-verify-clients` option enabled. 

```json
		"914": {
			"RegionID": 914,
			"RegionCode": "china-chengdu",
			"RegionName": "china-chengdu",
			"Nodes": [
				{
					"Name": "china-chengdu",
					"RegionID": 914,
					"HostName": "cd.example.cn",
					"STUNPort": 3478,
					"DERPPort": 1077
				}
			]
		}
```

tailscale acl

```json
			"914": {
				"RegionID":   914,
				"RegionCode": "china-chengdu",
				"RegionName": "china-chengdu",
				"Nodes": [
					{
						"Name":      "china-chengdu",
						"RegionID":  914,
					        "HostName": "cd.example.cn",
					        "STUNPort": 3478,
						"DERPPort":  1077,
						"CanPort80": false,
					},
				],
			},
```

**Comment by coadler** [comment]
Thanks for the info. It's unlikely that `wush` will work with DERPs that have `--verify-clients`, since `wush` nodes won't be registered in your Tailnet as they're randomly generated. There might be something we can do to integrate with Tailscale to register nodes, but it feels like at that point you might as well just use Tailscale.

Regarding the panic you ran into, it's definitely because you need to use the same derpmap on `wush serve` as you use on `wush cp`.

**Comment by ysicing** [comment]
Thank you! I'll try removing that parameter and see if it helps.
