### ISSUE TITLE
port-forward command crashes with nil pointer dereference

### ISSUE THREAD

**Issue by ProbablyFaiz** [coder/wush#82]
The `wush port-forward --tcp <port>:<port>` command crashes immediately after auth key entry with a nil pointer dereference error.

Steps to Reproduce:
1. Machine A: `wush serve` 
2. Machine B: `wush port-forward --tcp 5432:5432`
3. B: Enter auth key when prompted
4. B: Immediate crash occurs

Error Output:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x103a1ba40]

goroutine 1 [running]:
main.portForwardCmd.derpMap.func5.1(0x14000221600)
	github.com/coder/wush/cmd/wush/cp.go:104 +0x30
main.portForwardCmd.initAuth.func4.1(0x14000221600)
	github.com/coder/wush/cmd/wush/cp.go:74 +0x144
main.portForwardCmd.initLogger.func3.1(0x14000221600)
	github.com/coder/wush/cmd/wush/cp.go:45 +0x17c
github.com/coder/serpent.(*Invocation).run(0x14000221600, 0x140002f5bf8)
	github.com/coder/serpent@v0.8.0/command.go:487 +0xde0
github.com/coder/serpent.(*Invocation).run(0x14000221100, 0x140002f5bf8)
	github.com/coder/serpent@v0.8.0/command.go:407 +0x778
github.com/coder/serpent.(*Invocation).Run(0x14000221100)
	github.com/coder/serpent@v0.8.0/command.go:582 +0x118
main.main()
	github.com/coder/wush/cmd/wush/main.go:65 +0x4c0
```

I've reproduced this issue on both macOS 15.x and Ubuntu 22.x, and it occurs with other TCP ports as well.

This is on Wush v0.4.0, installed from the official binaries on GitHub releases. No custom DERP config is used.

**Comment by coadler** [comment]
Thanks for the detailed report! I'll fix this now
